# Generated by Django 3.1 on 2020-09-11 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address_1', models.CharField(blank=True, max_length=255)),
                ('address_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('zip_code', models.CharField(blank=True, max_length=18)),
                ('country', models.CharField(blank=True, max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='SportMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('which_form', models.CharField(default='CustomResult', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('when', models.DateTimeField()),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Upcoming'), (0, 'In Progress'), (-1, 'Ended'), (-3, 'Cancelled'), (2, 'Postponed'), (-2, 'Preponed')], default=1)),
                ('result', models.JSONField(null=True)),
                ('event_location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.location')),
                ('sport_mode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.sportmode')),
            ],
        ),
    ]
