# Generated by Django 3.1 on 2020-09-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200911_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='Lorem Ipsum dolor siet', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='address_1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(max_length=255),
        ),
    ]
