# Generated by Django 3.1 on 2020-09-03 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
