# Generated by Django 3.1 on 2020-09-04 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_delete_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='finished',
        ),
    ]
