# Generated by Django 3.1 on 2020-09-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(1, 'Upcoming'), (0, 'In Progress'), (-1, 'Ended'), (-3, 'Cancelled'), (2, 'Postponed'), (-2, 'Preponed')], default=1),
        ),
    ]
