# Generated by Django 3.1 on 2020-09-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200914_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportmode',
            name='which_form',
        ),
        migrations.AddField(
            model_name='sportmode',
            name='schema',
            field=models.JSONField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='result',
            field=models.JSONField(null=True),
        ),
    ]
