# Generated by Django 3.1 on 2020-09-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Upcoming'), (0, 'In Progress'), (-1, 'Ended'), (-3, 'Cancelled'), (2, 'Postponed'), (-2, 'Preponed')], default=1),
        ),
    ]
