# Generated by Django 3.1.1 on 2020-09-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_sportmode_result_handler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportmode',
            old_name='schema',
            new_name='result_schema',
        ),
        migrations.AddField(
            model_name='sportmode',
            name='display_schema',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
