# Generated by Django 3.1.1 on 2020-09-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200916_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/event_pictures'),
        ),
    ]
