# Generated by Django 3.1 on 2020-09-08 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20200905_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registration_schema', models.JSONField()),
                ('event_schema', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='result',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='sport_mode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='events.sportmode'),
            preserve_default=False,
        ),
    ]
