# Generated by Django 3.1 on 2020-09-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200908_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportmode',
            name='event_schema',
        ),
        migrations.RemoveField(
            model_name='sportmode',
            name='registration_schema',
        ),
        migrations.AddField(
            model_name='sportmode',
            name='which_form',
            field=models.CharField(default='CustomResult', max_length=100),
        ),
    ]
