# Generated by Django 3.1.1 on 2020-09-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20200924_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
