# Generated by Django 3.1.1 on 2020-09-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_registration_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Open'), (0, 'In Progress'), (-1, 'Ended'), (-3, 'Cancelled'), (2, 'Postponed'), (-2, 'Preponed'), (10, 'Full')], default=1),
        ),
    ]
