# Generated by Django 3.1.1 on 2020-09-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_event_participants_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payment_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
