# Generated by Django 3.1.1 on 2020-09-29 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_event_payment_cleared'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='payment_cleared',
            new_name='payment_released',
        ),
    ]
