# Generated by Django 3.1.1 on 2020-09-29 20:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20200929_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sponsored_prize',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
    ]
