# Generated by Django 3.1.1 on 2020-10-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_event_sponsored_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='publicly_visible_prize',
            field=models.BooleanField(default=True),
        ),
    ]
