runtime: python
env: flex
entrypoint: gunicorn -b :$PORT cucumber.wsgi

beta_settings:
    cloud_sql_instances: cucumbersports:us-east4:cucumbersports-db

runtime_config:
  python_version: 3

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "cucumbersports-cf0cce725274.json"