# Generated by Django 3.1.1 on 2020-09-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_registration_result_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='amount_won',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
