# Generated by Django 3.1 on 2020-09-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_registration_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='result',
            field=models.JSONField(null=True),
        ),
    ]
